codecov:
  strict_yaml_branch: main

ignore:
  - "SymbulationEmp/source/catch/**/*"
  - "SymbulationEmp/stats_scripts/**/*"
  - "SymbulationEmp/web/**/*"
  - "SymbulationEmp/source/Organism.h"
  - "SymbulationEmp/source/*.test.cc"
  - "SymbulationEmp/Empirical/**/*"
  - "SymbulationEmp/coverage_source/**/*"
  - "SymbulationEmp/source/test/**/*"
  - "SymbulationEmp/signalgp-lite/**/*"
