ignore:
  - "**/source/catch/**"
  - "**/source/json/**"
  - "stats_scripts/**/*"
  - "web/**/*"
  - "source/Organism.h"
  - "source/*.test.cc"
  - "Empirical/**/*"
  - "coverage_source/**/*"
  - "**/source/test/**"
  - "signalgp-lite/**/*"
